/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blackhole.glb --transform 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Blackhole(props) {
  const group = React.useRef()
  
  // 1. FIX: Update path to /models/
  const { nodes, materials, animations } = useGLTF('/models/blackhole-transformed.glb')
  
  const { actions } = useAnimations(animations, group)

  // 2. FIX: Play the animations when loaded
  useEffect(() => {
    // This loops through every animation in the file and plays it
    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.016}>
          <group name="Blackhole_ring" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Blackhole_ring_Blackhole_ring_0" geometry={nodes.Blackhole_ring_Blackhole_ring_0.geometry} material={materials.Blackhole_ring} />
          </group>
          <group name="Blackhole_skin_001" rotation={[-Math.PI / 2, 0, 0]} scale={0.959}>
            <mesh name="Blackhole_skin_001_Blackhole_skin_0" geometry={nodes.Blackhole_skin_001_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_002" rotation={[-Math.PI / 2, 0, 0]} scale={0.957}>
            <mesh name="Blackhole_skin_002_Blackhole_core_0" geometry={nodes.Blackhole_skin_002_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_003" rotation={[-Math.PI / 2, 0, 0]} scale={0.91}>
            <mesh name="Blackhole_skin_003_Blackhole_skin_0" geometry={nodes.Blackhole_skin_003_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_004" rotation={[-Math.PI / 2, 0, 0]} scale={0.908}>
            <mesh name="Blackhole_skin_004_Blackhole_core_0" geometry={nodes.Blackhole_skin_004_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_005" rotation={[-Math.PI / 2, 0, 0.96]} scale={0.9}>
            <mesh name="Blackhole_skin_005_Blackhole_skin_0" geometry={nodes.Blackhole_skin_005_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_006" rotation={[-Math.PI / 2, 0, -2.007]} scale={0.864}>
            <mesh name="Blackhole_skin_006_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_006_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_007" rotation={[-Math.PI / 2, 0, -2.007]} scale={0.866}>
            <mesh name="Blackhole_skin_007_Blackhole_core_0" geometry={nodes.Blackhole_skin_007_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_core001" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Blackhole_core001_Blackhole_core_0" geometry={nodes.Blackhole_core001_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_008" rotation={[-Math.PI / 2, 0, 0.087]} scale={0.845}>
            <mesh name="Blackhole_skin_008_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_008_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_009" rotation={[-Math.PI / 2, 0, -0.611]} scale={0.887}>
            <mesh name="Blackhole_skin_009_Blackhole_skin_0" geometry={nodes.Blackhole_skin_009_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_010" rotation={[-Math.PI / 2, 0, -2.531]} scale={0.929}>
            <mesh name="Blackhole_skin_010_Blackhole_skin_0" geometry={nodes.Blackhole_skin_010_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_011" rotation={[-Math.PI / 2, 0, -2.531]} scale={0.928}>
            <mesh name="Blackhole_skin_011_Blackhole_core_0" geometry={nodes.Blackhole_skin_011_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_012" rotation={[-Math.PI / 2, 0, 2.094]} scale={0.856}>
            <mesh name="Blackhole_skin_012_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_012_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_013" rotation={[-Math.PI / 2, 0, -2.967]} scale={0.835}>
            <mesh name="Blackhole_skin_013_Blackhole_ring2_0" geometry={nodes.Blackhole_skin_013_Blackhole_ring2_0.geometry} material={materials.Blackhole_ring2} />
          </group>
          <group name="Blackhole_core002" rotation={[-Math.PI / 2, 0, 0]} scale={0.928}>
            <mesh name="Blackhole_core002_Blackhole_ring2_0" geometry={nodes.Blackhole_core002_Blackhole_ring2_0.geometry} material={materials.Blackhole_ring2} />
          </group>
        </group>
        <mesh name="Blackhole_core_Blackhole_core_0" geometry={nodes.Blackhole_core_Blackhole_core_0.geometry} material={materials.Blackhole_core} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      </group>
    </group>
  )
}

// 3. FIX: Update preload path to /models/
useGLTF.preload('/models/blackhole-transformed.glb')