/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pixel_planet_1.glb --transform 
Files: pixel_planet_1.glb [60.64KB] > F:\my-portfolio\public\models\pixel_planet_1-transformed.glb [41.24KB] (32%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-ogle-2005-blg-390l-b-5cd60f79fd704274a68e8f76405f2d6e
Title: Pixel Planet OGLE-2005-BLG-390L b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pixel_planet_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/pixel_planet_1-transformed.glb')
