/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet.glb --transform 
Files: planet.glb [2.84MB] > F:\my-portfolio\public\models\planet-transformed.glb [307.34KB] (89%)
Author: WeSVa (https://sketchfab.com/WSVideoCarta)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/fire-planet-fa3ff413c802481b8a1a19fab164339b
Title: Fire Planet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere__0.geometry} material={materials['Scene_-_Root']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/planet-transformed.glb')
