/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet.glb --transform 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Planet(props) {
  const group = useRef()
  // Ensure path is correct
  const { nodes, materials } = useGLTF('/models/planet-transformed.glb')

  useFrame((state, delta) => {
    if (group.current) {
      // Planet rotation
      group.current.rotation.y += delta * 0.1; 
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={useGLTF('/models/planet-transformed.glb').scene} />
    </group>
  )
}

useGLTF.preload('/models/planet-transformed.glb')