/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 satellite.glb --transform 
Files: satellite.glb [3.69MB] > F:\my-portfolio\public\models\satellite-transformed.glb [360.28KB] (90%)
Author: Wolf van Veen (https://sketchfab.com/wolfvanveen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satellite-9be57c6e0b48411ebba7725c8267f264
Title: Satellite
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/satellite-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/satellite-transformed.glb')
