/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 satellite.glb --transform 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

// Renaming generic "Model" to "Satellite"
export function Satellite(props) {
  const group = useRef()
  // 1. FIX PATH: Ensure it points to /models/
  const { nodes, materials } = useGLTF('/models/satellite-transformed.glb')

  // 2. ADD ANIMATION: Slow drift
  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.2; 
      group.current.rotation.z += delta * 0.05; 
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Use primitive to remain safe against different GLB structures.
         If you want to use specific meshes (like solar panels), you can use nodes.MeshName 
      */}
      <primitive object={useGLTF('/models/satellite-transformed.glb').scene} />
    </group>
  )
}

useGLTF.preload('/models/satellite-transformed.glb')