/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 station.glb --transform 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Station(props) {
  const group = useRef()
  // 1. FIX PATH
  const { nodes, materials } = useGLTF('/models/station-transformed.glb')

  // 2. ADD ANIMATION: Slow constant spin
  useFrame((state, delta) => {
    if (group.current) {
       group.current.rotation.y -= delta * 0.05; 
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={useGLTF('/models/station-transformed.glb').scene} />
    </group>
  )
}

useGLTF.preload('/models/station-transformed.glb')