/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 station.glb --transform 
Files: station.glb [3.27MB] > F:\my-portfolio\public\models\station-transformed.glb [362.73KB] (89%)
Author: WeSVa (https://sketchfab.com/WSVideoCarta)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/space--station-517e74a0214740c8adb38557d4ee9b8b
Title: Space_ Station
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/station-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloner_6__0.geometry} material={materials['Scene_-_Root']} position={[0, 3.875, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/station-transformed.glb')
