/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.glb --transform 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

// Renamed "Model" to "SpaceshipModel" for clarity
export function SpaceshipModel(props) {
  // Ensure this path matches EXACTLY where your file is in /public/models/
  const { nodes, materials } = useGLTF('/models/spaceship-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      {/* Note: I kept your rotations, but if the ship points backwards, change rotation Y to 0 or Math.PI */}
      <mesh geometry={nodes.Cube010_BASE_0.geometry} material={materials.BASE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube003_WINGS_0.geometry} material={materials.WINGS} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/spaceship-transformed.glb')